sudo: required
services:
  - docker

before_install:
  - docker build -t elpabl0s/docker-react -f Dockerfile.dev .

script:
  - docker run elpabl0s/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-249397701597"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
          secure: : "$AWS_SECRET_KEY"

