sudo: required
services:
        - docker

before_install:
        - docker build -t elpab0s/docker-react -f Dockerfile.dev .

script:
        - docker run elpabl0s/docker-react npm run test -- --coverage
